//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdamDal
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Products = new HashSet<Product>();
            this.BrandFollowers = new HashSet<BrandFollower>();
            this.TrendingProducts = new HashSet<TrendingProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public string UserName { get; set; }
    [ScriptIgnore]
        public virtual Category Category { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<BrandFollower> BrandFollowers { get; set; }
        public virtual ICollection<TrendingProduct> TrendingProducts { get; set; }
    }
}
