//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdamDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Brands = new HashSet<Brand>();
            this.Customer_AreaOfInterest = new HashSet<Customer_AreaOfInterest>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Brand> Brands { get; set; }
        public virtual ICollection<Customer_AreaOfInterest> Customer_AreaOfInterest { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
