//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdamDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_AreaOfInterest
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int AreaOfInterest { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
