//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdamDal
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    
    public partial class FeatureSentiment
    {
        public int Id { get; set; }
        public int PId { get; set; }
        public string Feature { get; set; }
        public int Sentiment { get; set; }
        public int Count { get; set; }
     [ScriptIgnore]
        public virtual Product Product { get; set; }
    }
}
