//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdamDal
{
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    
    public partial class Product
    {
        public Product()
        {
            this.Product_Specification = new HashSet<Product_Specification>();
            this.ProductReviews = new HashSet<ProductReview>();
            this.FeatureSentiments = new HashSet<FeatureSentiment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public string ImageUrl { get; set; }
        public string Price { get; set; }
        public string ReviewSummary { get; set; }
        public string ReleaseDate { get; set; }
        public Nullable<double> Rating { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Product_Specification> Product_Specification { get; set; }
        public virtual ICollection<ProductReview> ProductReviews { get; set; }
         [ScriptIgnore]
        public virtual Brand Brand { get; set; }
        public virtual ICollection<FeatureSentiment> FeatureSentiments { get; set; }
    }
}
